import { indexLang } from './indexLang.js'

const { navEs, navEn, homeEs, homeEn, toursEs, toursEn, uyuni_1_Es, uyuni_1_En, uyuni_2_Es, uyuni_2_En, uyuni_3_Es, uyuni_3_En, uyuni_1_private_Es, uyuni_1_private_En,
    uyuni_3_private_Es, uyuni_3_private_En, uyuni_3_sanPedro_Es, uyuni_3_sanPedro_En, uyuni_estrellas_Es, uyuni_estrellas_En, uyuni_amanecer_Es, uyuni_amanecer_En, aboutEs, aboutEn, galeryEs, galeryEn, slider_badge_es, slider_badge_en, testimonials_1_Es, testimonials_1_En, testimonials_2_Es, testimonials_2_En, testimonials_3_Es, testimonials_3_En, testimonials_4_Es, testimonials_4_En, testimonials_5_Es, testimonials_5_En, testimonials_6_Es, testimonials_6_En, footerEs, footerEn } = indexLang
const tourDetailEs = {
    '#tour-detail-back': 'Volver',
    '#tour-feature-duration-label': 'Duración',
    '#tour-feature-type-label': 'Tipo de Tour',
    '#tour-feature-group-size-label': 'Tamaño del Grupo',
    '#tour-feature-languages-label': 'Guía turístico',
    '#tour-section-description-title': 'Descripción',
    '#tour-section-recommendations-title': 'Recomendaciones',
    '#tour-section-itinerary-title': 'Itinerario',
    '#tour-section-included-title': 'Qué está incluido',
    '#tour-section-excluded-title': 'Qué no está incluido',
    '#tour-section-prices-title': 'Precios',
    '#tour-section-prices-subtitle': 'Precios por Persona (Base Doble)',
    '#tour-section-faqs-title': 'Preguntas Frecuentes',


    '#tour-booking-title': 'Reservar o Consultar',
    '#tour-booking-name': 'Nombre Completo *',
    '#tour-booking-email': 'Correo Electrónico *',
    '#tour-booking-date': 'Fecha de Viaje *',
    '#tour-booking-passengers': 'Pasajeros *',
    '#tour-booking-message': 'Mensaje / Requerimientos *',
    '#tour-contact-title': 'Información de Contacto',
    '#tour-contact-email': 'Email',
    '#tour-contact-email-link': 'lamiratoursoficial1@gmail.com',
    '#tour-contact-phone': 'Teléfono',
    '#tour-contact-phone-link': '+591 63722016',
    '#tour-contact-address': 'Dirección',
    '#tour-contact-address-text': 'Av. Ferroviaria entre calle Bolivar y Arce, Uyuni, Potosí, Bolivia',
    '#tour-booking-submit': 'Enviar',
    '#booking-passenger-placeholder': 'Seleccione pasajeros',
    '#passenger-1': '1 Pasajero',
    '#passenger-2': '2 Pasajeros',
    '#passenger-3': '3 Pasajeros',
    '#passenger-4': '4 Pasajeros',
    '#passenger-5': '5 Pasajeros',
    '#passenger-6': '6 Pasajeros (Grupo Máximo)',
    '#booking-message': 'Especifica necesidades dietéticas, si requieres guía en inglés, etc...',
}
const tourDetailEn = {
    '#tour-detail-back': 'Back',
    '#tour-feature-duration-label': 'Duration',
    '#tour-feature-type-label': 'Tour Type',
    '#tour-feature-group-size-label': 'Group Size',
    '#tour-feature-languages-label': 'Tour guide',
    '#tour-section-description-title': 'Description',
    '#tour-section-recommendations-title': 'Recommendations',
    '#tour-section-itinerary-title': 'Itinerary',
    '#tour-section-included-title': 'What is included',
    '#tour-section-excluded-title': 'What is not included',
    '#tour-section-prices-title': 'Prices',
    '#tour-section-prices-subtitle': 'Prices per Person (Double Occupancy)',
    '#tour-section-booking-title': 'Book or Inquire',
    '#tour-section-faqs-title': 'Frequently Asked Questions',

    '#tour-booking-title': 'Book or Inquire',
    '#tour-booking-name': 'Full Name *',
    '#tour-booking-email': 'Email *',
    '#tour-booking-date': 'Travel Date *',
    '#tour-booking-passengers': 'Passengers *',
    '#tour-booking-message': 'Message / Requirements *',
    '#tour-contact-title': 'Contact Information',
    '#tour-contact-email': 'Email',
    '#tour-contact-email-link': tourDetailEs['#tour-contact-email-link'],
    '#tour-contact-phone': 'Phone',
    '#tour-contact-phone-link': tourDetailEs['#tour-contact-phone-link'],
    '#tour-contact-address': 'Address',
    '#tour-contact-address-text': 'Ferroviaria Avenue between Bolivar and Arce streets, Uyuni, Potosí, Bolivia',
    '#tour-booking-submit': 'Send',
    '#booking-passenger-placeholder': 'Select passengers',
    '#passenger-1': '1 Passenger',
    '#passenger-2': '2 Passengers',
    '#passenger-3': '3 Passengers',
    '#passenger-4': '4 Passengers',
    '#passenger-5': '5 Passengers',
    '#passenger-6': '6 Passengers (Group Maximum)',
    '#booking-message': 'Specify dietary needs, if you require a guide in English, etc...',
}

export const languages = {
    es: {
        //index.html
        ...navEs,
        ...homeEs,
        ...toursEs,
        ...uyuni_1_Es,
        ...uyuni_2_Es,
        ...uyuni_3_Es,
        ...uyuni_1_private_Es,
        ...uyuni_3_private_Es,
        ...uyuni_3_sanPedro_Es,
        ...uyuni_estrellas_Es,
        ...uyuni_amanecer_Es,
        ...aboutEs,
        ...slider_badge_es,
        ...testimonials_1_Es,
        ...testimonials_2_Es,
        ...testimonials_3_Es,
        ...testimonials_4_Es,
        ...testimonials_5_Es,
        ...testimonials_6_Es,
        ...footerEs,
        ...galeryEs,
        //ofertas
        ...tourDetailEs,
    },
    en: {
        //index.html
        ...navEn,
        ...homeEn,
        ...toursEn,
        ...uyuni_1_En,
        ...uyuni_2_En,
        ...uyuni_3_En,
        ...uyuni_1_private_En,
        ...uyuni_3_private_En,
        ...uyuni_3_sanPedro_En,
        ...uyuni_estrellas_En,
        ...uyuni_amanecer_En,
        ...aboutEn,
        ...slider_badge_en,
        ...testimonials_1_En,
        ...testimonials_2_En,
        ...testimonials_3_En,
        ...testimonials_4_En,
        ...testimonials_5_En,
        ...testimonials_6_En,
        ...footerEn,
        ...galeryEn,
        //ofertas.html
        ...tourDetailEn,

    }
};
